Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using StoreQR.Models;
using System.Diagnostics;

namespace StoreQR.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;

        public AboutController(ILogger<AboutController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/FamilyMemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreQR.Data;
using StoreQR.Models;
using System;
using System.Security.Claims;

namespace StoreQR.Controllers
{
    public class FamilyMemberController : Controller
    {
        private readonly ILogger<FamilyMemberController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public FamilyMemberController(ILogger<FamilyMemberController> logger, 
            ApplicationDbContext context,
            UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }
        public IActionResult Index(FamilyMember viewModel)
        {
            //Hämta användarens id med hjälp av user manager
            string? currentUserId = _userManager.GetUserId(HttpContext.User);
            if (currentUserId != null)
            {
               //Hämtar alla användarens hushållsmedlemmar
               var familyMembers = _context.GetFamilyMembersFilteredByUserId(currentUserId);
                if (familyMembers != null)
                {
                    return View(familyMembers);
                }
            }
            return View(viewModel);
            
        }

        //Hämta create-vy för familjemedlemmar
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        //Skicka create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FamilyMember model)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            if (userId != null)
            {
                model.UserId = userId;
                if (ModelState.IsValid)
                {
                    try
                    {
                        model.Name = model.Name.Trim();
                        model.UserId = userId;

                        _context.FamilyMember.Add(model);
                        await _context.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error saving FamilyMember: {ex.Message}");
                    }
                }
                else 
                { 
                    return View(model); 
                }
            }
            else
            {
                return BadRequest("UserId saknas.");
            }
            return View(model);
        }

        //Get FamilyMemberEdit
        [Authorize]
        public async Task<IActionResult> Edit (int Id)
        {
            string? currentUserId = _userManager.GetUserId(HttpContext.User);

            if (currentUserId == null)
            {
                _logger.LogWarning("User is not authorized.");
                return Forbid(); // Return 403 Forbidden status if the user is not authorized.
            }

            var familyMember = await _context.GetFamilyMemberAsync(Id, currentUserId);
            if (familyMember == null)
                {
                    Console.WriteLine("Familjemedlem saknas");
                    return NotFound();
            }

            return View(familyMember);
        }

        //POST FamilyMember/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (int Id, FamilyMember model)
        {
            if (Id != model.Id)
            {
                return NotFound();
            }

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest("UserId saknas");
            }

            try
            {
                if(ModelState.IsValid)
                {
                    try
                    {
                        //Hämta nuvarande familjemedlemsobjekt

                        var existingFamilyMember = await _context.FamilyMember.FindAsync(Id);

                        if (existingFamilyMember == null)
                        {
                            return NotFound();
                        }

                        //Uppdaterar det som användaren skrivit in
                        existingFamilyMember.Name = model.Name;

                        //Spara ändringar till databas
                        _context.FamilyMember.Update(existingFamilyMember);
                        await _context.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    catch (DbUpdateException ex)
                    {
                        _logger.LogError(ex, $"Error updating FamilyMember with ID {Id}. Database update error.");
                        return View(model);
                    }
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }


        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest("UserId saknas");
            }

            var FamilyMember = await _context.FamilyMember.FindAsync(id);
            if (FamilyMember == null)
            {
                return NotFound();
            }
            try
            {
                await _context.DeleteFamilyMemberByIdAsync(id, userId);
                TempData["DeleteSuccessMessage"] = "Din hushållsmedlem raderades.";
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, $"Error deleting FamilyMember with ID {id}. Database update error.");
                TempData["DeleteErrorMessage"] = "Det gick inte att radera din hushållsmedlem.";
                return View();
            }

            return RedirectToAction("Index");
        }

    }



}

Controllers/StoringController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreQR.Data;
using StoreQR.Models;
using System.Security.Claims;
using X.PagedList;

namespace StoreQR.Controllers
{
    public class StoringController : Controller
    {
        private readonly ILogger<StoringController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public StoringController(ILogger<StoringController> logger, 
            ApplicationDbContext context,
            UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        public IActionResult Index(StoringUnit viewModel, int? page)
        {
            //Hämta användarens id med hjälp av user manager
            string? currentUserId = _userManager.GetUserId(HttpContext.User);
            //Sidor i pagineringen
            int pageSize = 10;
            if (currentUserId != null)
            {
                var storageUnits = _context.GetStorageUnitsFilteredByUserId(currentUserId);
                var pagedStorageUnits = storageUnits.ToPagedList(page ?? 1, pageSize);

                return View(pagedStorageUnits);
            }
           return View(viewModel);
        }

        //Hämta create-vy för förvaringsutrymmen
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (StoringUnit model)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            if(userId != null)
            {
                model.UserId = userId;
                if(ModelState.IsValid)
                {
                    try
                    {
                        if (model.StorageImageFile != null && model.StorageImageFile.Length > 0)
                        {
                            using (var memoryStream = new MemoryStream())
                            {
                                await model.StorageImageFile.CopyToAsync(memoryStream);
                                //Gör om bytearrayen till en base64sträng
                                var base64String = Convert.ToBase64String(memoryStream.ToArray());

                                model.StorageImage = base64String;
                            }
                        } else
                        {
                            //Sätt StorageImage till null om ingen bild läggs in
                            model.StorageImage = null;
                        }

                        model.StorageName = ToPascalCase(model.StorageName.Trim());
                        model.StorageDescription = model.StorageDescription.Trim();
                        model.QRCode = model.QRCode;

                        _context.StoringUnit.Add(model);
                        await _context.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error saving StoringUnit: {ex.Message}");
                    }
                }
                else
                {
                    foreach (var modelStateEntry in ModelState.Values)
                    {
                        foreach (var error in modelStateEntry.Errors)
                        {
                            Console.WriteLine($"Error: {error.ErrorMessage}");
                        }
                    }
                }
            }
            else
            {
                return BadRequest("UserId saknas");
            }
            return View(model);
        }

        public static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;

            // Split the string into words
            string[] words = input.Split(new char[] { ' ', '_', '-' }, StringSplitOptions.RemoveEmptyEntries);

            // Capitalize the first letter of each word
            for (int i = 0; i < words.Length; i++)
            {
                words[i] = char.ToUpper(words[i][0]) + words[i].Substring(1);
            }

            // Join the words back into a single string with spaces
            return string.Join(" ", words);
        }

        //Get StoringUnit Edit
        public async Task<IActionResult> Edit (int StorageId)
        {
            string? currentUserId = _userManager.GetUserId(HttpContext.User);

            if (currentUserId == null)
            {
                _logger.LogWarning("User is not authorized.");
                return Forbid(); // Return 403 Forbidden status if the user is not authorized.
            }

            var storingUnits = await _context.GetStoringUnitAsync(StorageId, currentUserId);

            if (storingUnits == null || !storingUnits.Any())
            {
                Console.WriteLine("Förvaringsutrymme saknas");
            }
            return View(storingUnits);
        }

        //POST StoringUnit Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (int StorageId, StoringUnit model)
        {
            if (StorageId != model.StorageId)
            {
                return NotFound();
            }

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                return BadRequest("UserId saknas");
            }

            try
            {
                if(ModelState.IsValid)
                {
                    try
                    {
                        //Hämta nuvarande förvaringsutrymmeobjekt från databasen
                        var existingStoringUnit = await _context.StoringUnit.FindAsync(StorageId);

                        if (existingStoringUnit == null)
                        {
                            return NotFound();
                        }

                        //Uppdaterar det som användaren skrivit in
                        existingStoringUnit.StorageName = model.StorageName;
                        existingStoringUnit.StorageDescription = model.StorageDescription;

                        //Spara ändringar till databas
                        _context.StoringUnit.Update(existingStoringUnit);
                        await _context.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                    catch (DbUpdateException ex)
                    {
                        _logger.LogError(ex, $"Error updating StoringUnit with ID {StorageId}. Database update error.");
                        return View(model);
                    }
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }
        
        [Authorize]
        public async Task<IActionResult> Delete(int StorageId)
        {
            string? currentUserId = _userManager.GetUserId(HttpContext.User);

            if (currentUserId == null)
            {
                _logger.LogWarning("User is not authorized.");
                return Forbid(); // Return 403 Forbidden status if the user is not authorized.
            }

            var storingUnits = await _context.GetStoringUnitAsync(StorageId, currentUserId);

            if (storingUnits == null)
            {
                Console.WriteLine("Förvaringsutrymme saknas");
            }
            var storingUnit = storingUnits?.First();


            return View("Delete", storingUnit);
        }
        //Delete StoringUnit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed (int StorageId)
        {
            if (StorageId == 0)
            {
                return NotFound();
            }
            string? currentUserId = _userManager.GetUserId(HttpContext.User);

            if (currentUserId == null)
            {
                _logger.LogWarning("User is not authorized.");
                return Forbid(); // Return 403 Forbidden status if the user is not authorized.
            }

            var storingUnit = await _context.StoringUnit.FindAsync(StorageId);

            if (storingUnit == null)
            {
                return NotFound();
            }
            try
            {
                await _context.DeleteStorageUnitByIdAsync(StorageId, currentUserId);
                TempData["DeleteSuccessMessage"] = "Dtt förvaringsutrymme raderades.";
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex, $"Error deleting StoingUnit with ID {StorageId}. Database update error.");
                TempData["DeleteErrorMessage"] = "Det gick inte att radera ditt förvaringsutrymme.";
                return View(storingUnit);
            }
            return RedirectToAction("Index");

        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="author" content="Susanne Arnetz Linder" />
    <meta name="keywords" content="ASP.NET, SQL, JavaScript, StoreQR" />
    <meta property="og:title" content="StoreQR" />
    <meta property="og:image" content="/lib/StoreQR.png" />
    <meta property="og:url" content="https://www.storeqr.se" />
    <meta property='og:description' content='Storing application that helps you to not loose your shit. With StoreQR, the user can create an account and add clothing items, storing units and family member. They can register where they have stored their clothing item and also assign clothing items to family members.' />

    <title>@ViewData["Title"] - StoreQR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreQR.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/88669a913c.js" crossorigin="anonymous"></script>

</head>
<body>
    <header class="header">
        <nav class="navbar navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a id="headerlink" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="StoreQRLogo" src="/lib/StoreQRLogo.png" alt="Logo" />
                </a>

                <button id="navbarButton" class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation" onclick="toggleNavbarIcon()">
                    <span id="navbarSpan1"></span>
                    <span id="navbarSpan2"></span>
                    <span id="navbarSpan3"></span>
                </button>
                <div id="addShow"class="navbar-collapse collapse justify-content-between p-3">
                    @if (SignInManager.IsSignedIn(User))
                    {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a id="headerlink1" class="nav-link mt-3" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a id="headerlink2" class="nav-link mt-3" asp-area="" asp-controller="FamilyMember" asp-action="Index">Mina hushållsmedlemmar</a>
                        </li>
                        <li>
                            <a id="headerlink3" class="nav-link mt-3" asp-area="" asp-controller="Clothing" asp-action="Index">Kläder</a>
                        </li>
                        <li>
                            <a id="headerlink4" class="nav-link mt-3" asp-area="" asp-controller="Storing" asp-action="Index">Förvaringsutrymmen</a>
                        </li>
                        <li>
                                <a id="headerlink5" class="nav-link mt-3" asp-area="" asp-controller="About" asp-action="Index">Om StoreQR</a>
                        </li>
                    </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-3">
            <main role="main" class="pb-3 mb-3">
                @RenderBody()
            </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom StoreQRFooter">
        <div class="desktop-only container">
        <div class="d-flex flex-row">
            <ul class="list-unstyled d-flex mb-0 justify-content-between">
                <li class="m-3">
                    <span>
                        <i class="fa-solid fa-location-dot" aria-hidden="true"></i>
                    </span>
                    Stockholm
                </li>
                <li class="m-3">
                    <a href="https://github.com/arnetzlinder" class="text-decoration-none text-reset">
                            <span>
                                <i class="fa-brands fa-github" aria-hidden="true"></i>
                            </span>
                            Github
                        </a>
                 </li>
                <li class="m-3">
                    <a href="https://www.linkedin.com/in/susanne-arnetz-linder-999a2481/" class="text-decoration-none text-reset">
                            <span>
                                <i class="fa-brands fa-linkedin" aria-hidden="true"></i>
                            </span>
                            LinkedIn
                        </a>
                 </li>
                <li class="m-3">
                    <a href="https://portfolio.arnetzlinder.com" class="text-decoration-none text-reset">
                    <span>
                            <i class="fa-solid fa-briefcase" aria-hidden="true"></i>
                    </span>
                        Portfolio
                        </a>
                    </li>

            </ul>
            <div class="m-3 ms-auto">
                <p>&copy; 2024 - StoreQR</p>
            </div>
            </div>
        </div>
        <div class="mobile-only container">
            <div class="d-flex flex-row">
                <ul class="list-unstyled d-flex mb-0 justify-content-between">
                    <li class="m-3">
                        <a href="https://github.com/arnetzlinder" class="text-decoration-none text-reset">
                            <span>
                                <i class="fa-brands fa-github" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="m-3">
                        <a href="https://www.linkedin.com/in/susanne-arnetz-linder-999a2481/" class="text-decoration-none text-reset">
                            <span>
                                <i class="fa-brands fa-linkedin" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="m-3">
                        <a href="https://portfolio.arnetzlinder.com" class="text-decoration-none text-reset">
                            <span>
                                <i class="fa-solid fa-briefcase" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>

                </ul>
                <div class="m-3 ms-auto">
                    <p>&copy; 2024 - StoreQR</p>
                </div>
            </div>
            </div>
    </footer>
    <style>
        .navbar-toggler {
            background-color: transparent;
            border: none;
            padding: 10px;
            cursor: pointer;
            border-color: transparent !important;
            outline: none !important;
            transition: transform .6s cubic-bezier(.165,.84,.44,1);
        }

        .navbar-light .navbar-toggler
        {
            box-shadow:none;
        }

        .navbar-toggler span {
            display: block;
            width: 40px;
            height: 3px;
            background-color: white;
            margin-top: 5px;
            transition: transform .6s cubic-bezier(.165,.84,.44,1), opacity .3s cubic-bezier(.165,.84,.44,1), background-color .6s cubic-bezier(.165,.84,.44,1);
        }

        .navbar-collapse {
            transition: height 0.3s ease, opacity 0.2s ease-in-out;
            visibility: hidden;
        }

            .navbar-collapse.show {
                transition: height 0.3s ease, opacity 0.5s ease-in-out;
                opacity: 1;
                visibility: visible;
            }

        .collapse:not(.show) {
            display: block;
            padding: 1rem;
        }

        #headerlink {
            color: white;
        }

        #headerlink1 {
            color: white;
        }

        #headerlink2 {
            color: white;
        }
        #headerlink3 {
            color: white;
        }

        #headerlink4 {
            color: white;
        }

        #headerlink5 {
            color: white;
        }
        #navbarSpan1 {
            transform: translateY(-6px);
        }

        #navbarSpan2 {
            transform-origin: 100% 50%;
            transform: scaleX(.8);
        }

        #navbarSpan3 {
            transform: translateY(6px);
        }

        .navbar-toggler:hover #navbarSpan2 {
            transform: scale(1);
            transition: 0.5s ease-in-out;
        }

        .navbar-toggler.active {
            transform: rotate(-180deg);
        }

            .navbar-toggler.active #navbarSpan1 {
                transform: translateY(8px) rotate(45deg);
            }

            .navbar-toggler.active #navbarSpan2 {
                opacity: 0;
            }

            .navbar-toggler.active #navbarSpan3 {
                transform: translateY(-8px) rotate(-45deg);
            }

        @@media screen and (max-width: 576px) {
            .desktop-only {
                display: none !important;
            }

            .mobile-only {
                display: block;
            }
        }

        @@media screen and (min-width: 577px) {
            .desktop-only {
                display: block !important;
            }

            .mobile-only {
                display: none;
            }
        }

        
    </style>
   <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>

    <script>
        function toggleNavbarIcon() {
            var button = document.getElementById('navbarButton');
            var menu = document.getElementById('addShow');
            button.classList.toggle('active');
            menu.classList.toggle('show');
        }
    
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>