Models/ClothingViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace StoreQR.Models
{
    public class ClothingViewModel
    {
        public int ClothingId { get; set; }
        public string UserId { get; set; } = string.Empty;
        [DisplayName("Bild")]
        [DataType(DataType.Upload)]
        public string? ClothingImage { get; set; } = string.Empty;
        public string ClothingImageFormat { get; set; } = string.Empty;
        //[DisplayName("Bild")]
        //public byte[]? ClothingImage { get; set; }
        [DisplayName("Beskrivning:")]
        public string ClothingName { get; set; } = string.Empty;

        //public string QRCode { get; set; } = string.Empty;

        [DisplayName("Märke:")]
        public string ClothingBrand { get; set; } = string.Empty;

        [DisplayName("Storlek:")]
        public string ClothingSize { get; set; } = string.Empty;

        [DisplayName("Färg:")]
        public string ClothingColor { get; set; } = string.Empty;

        [DisplayName("Säsong:")]
        public string Season { get; set; } = string.Empty;

        [DisplayName("Material:")]
        public string ClothingMaterial { get; set; } = string.Empty;

        [DisplayName("Typ av plagg:")]
        public string TypeOfClothing { get; set; } = string.Empty;
        [DisplayName("Tillhör:")]
        public int ClothingUserId { get; set; }
        [DisplayName("Tillhör:")]
        public string FamilyMemberName {  get; set; } = string.Empty;

        public string FamilyUserId { get; set; } = string.Empty;

        public int FamilyMemberId { get; set; }

        public int? StorageId { get; set; }
        public string StorageName { get; set; } = string.Empty;

        public string QRCode {  get; set; } = string.Empty;

    }
}

Controllers/ClothingController.cs
using Microsoft.AspNetCore.Mvc;
using StoreQR.Data;
using StoreQR.Models;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreQR.Interface;
using Microsoft.CodeAnalysis.Elfie.Extensions;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using X.PagedList;

namespace StoreQR.Controllers
{
    [Authorize]
    public class ClothingController : Controller
    {
        private readonly ILogger<ClothingController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IClothingFilterService _filterService;
        private readonly UserManager<IdentityUser> _userManager;


        public ClothingController(ILogger<ClothingController> logger, 
            ApplicationDbContext context, 
            IClothingFilterService filterService,
            UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _filterService = filterService ?? throw new ArgumentNullException(nameof(filterService));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        //[Authorize]
        public IActionResult Index(ClothingViewModel viewModel, bool? ResetFilters, int? page)
        {
            //Hämta användarens id med hjälp av user manager
            string? currentUserId = _userManager.GetUserId(HttpContext.User);
            if (currentUserId != null)
            {
                //Hämtar alla värden först
                var familyMembersAndStorage = _context.CombineFamilyNameAndStorageNameByUserId(currentUserId);
                
                //Sidor i pagineringen
                int pageSize = 9;

                //Plockar ut distinkta värden för familjemedlemmar
                var distinctFamilyMembers = familyMembersAndStorage
                    .Select(c => new
                    {
                        ClothingBrand = c.ClothingBrand,
                        ClothingSize = c.ClothingSize,
                        ClothingColor = c.ClothingColor,
                        Season = c.Season,
                        ClothingMaterial = c.ClothingMaterial,
                        TypeOfClothing = c.TypeOfClothing,
                        FamilyMemberName = c.FamilyMemberName,
                        ClothingImage = c.ClothingImage,
                    })
                    .Distinct()
                    .ToList();
                
                //Plockar ut distinkta värden för förvaringsutrymmen
                var storageUnits = familyMembersAndStorage.Select(c => new
                {
                    StorageId = c.StorageId,
                    StorageName = c.StorageName,
                    
                })
                    .Distinct()
                    .ToList();
                

                //var clothingInfo = _context.GetFamilyMembersByUserId(currentUserId).ToList();
                //var storageUnitNames = _context.GetStorageNameByUserId(currentUserId).ToList();
                ViewBag.DistinctBrands = distinctFamilyMembers.Select(c => c.ClothingBrand).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctSizes = distinctFamilyMembers.Select(c => c.ClothingSize).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctColors = distinctFamilyMembers.Select(c => c.ClothingColor).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctSeasons = distinctFamilyMembers.Select(c => c.Season).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctMaterials = distinctFamilyMembers.Select(c => c.ClothingMaterial).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctTypesOfClothing = distinctFamilyMembers.Select(c => c.TypeOfClothing).Distinct().OrderBy(x => x).ToList();
                ViewBag.DistinctFamilyMemberName = distinctFamilyMembers.Select(c => c.FamilyMemberName).Distinct().OrderBy(x => x).ToList();
                ViewBag.StorageUnitName = storageUnits.Select(c => c.StorageName).Distinct().OrderBy(x => x).ToList();

               

                if (ResetFilters.HasValue && ResetFilters.Value)
                {
                    // Återställ filter om knappen återställ klickats på
                    viewModel.FamilyMemberName = "";
                    viewModel.ClothingBrand = "";
                    viewModel.ClothingSize = "";
                    viewModel.ClothingColor = "";
                    viewModel.Season = "";
                    viewModel.ClothingMaterial = "";
                    viewModel.TypeOfClothing = "";
                    viewModel.StorageName = "";
                }


                //Om alla fält är tomma eller alla är vald
                if (viewModel.ClothingBrand == "" &&
                    viewModel.ClothingSize == "" &&
                    viewModel.ClothingColor == "" &&
                    viewModel.Season == "" &&
                    viewModel.ClothingMaterial == "" &&
                    viewModel.TypeOfClothing == "" &&
                    viewModel.FamilyMemberName == "" &&
                    viewModel.StorageName == "")
                {
                    //Hämtar alla träffar om inget val gjorts eller om användaren väljer alla märken
                    var allClothingItems = _filterService.GetAllClothingItems();
                    var pagedClothingItems = allClothingItems.ToPagedList(page ?? 1, pageSize);

                    var pagedClothingViewModels = new StaticPagedList<ClothingViewModel>(
                        pagedClothingItems.Select(item => new ClothingViewModel 
                        {
                            ClothingId = item.ClothingId,
                            ClothingName = item.ClothingName,
                            ClothingImage = item.ClothingImage,
                            ClothingBrand = item.ClothingBrand,
                            ClothingSize = item.ClothingSize,
                            ClothingColor = item.ClothingColor,
                            Season = item.Season,
                            ClothingMaterial = item.ClothingMaterial,
                            TypeOfClothing = item.TypeOfClothing,
                            FamilyMemberName = item.FamilyMemberName,
                            StorageName = item.StorageName
                        }),
                        pagedClothingItems.GetMetaData()
                    );
                    return View(pagedClothingViewModels);
                }
                else
                {
                    var filteredClothingItems = _filterService.GetFilteredClothingItems(
                                  viewModel.ClothingBrand,
                                  viewModel.ClothingSize,
                                  viewModel.ClothingColor,
                                  viewModel.Season,
                                  viewModel.ClothingMaterial,
                                  viewModel.TypeOfClothing,
                                  viewModel.FamilyMemberName,
                                  viewModel.StorageName
                              );



                    var pagedFilteredClothingItems = filteredClothingItems.ToPagedList(page ?? 1, pageSize);

                    var pagedFilteredClothingViewModels = new StaticPagedList<ClothingViewModel>(
                        pagedFilteredClothingItems.Select(item => new ClothingViewModel { 
                        ClothingId = item.ClothingId,
                        ClothingName = item.ClothingName,
                        ClothingImage = item.ClothingImage,
                        ClothingBrand = item.ClothingBrand,
                        ClothingSize = item.ClothingSize,
                        ClothingColor = item.ClothingColor,
                        Season = item.Season,
                        ClothingMaterial = item.ClothingMaterial,
                        TypeOfClothing = item.TypeOfClothing,
                        FamilyMemberName = item.FamilyMemberName,
                        StorageName = item.StorageName
                        }),
                        pagedFilteredClothingItems.GetMetaData()
                    );

                    return View(pagedFilteredClothingViewModels);
                }
            } else
            {
                Console.WriteLine("Something went wrong");
                throw new Exception("Something went wrong");
            }
           
          
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Create()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (!string.IsNullOrEmpty(userId))
            {
                var familyMemberNames = _context.FamilyMember
                    .Where(fm => fm.UserId == userId)
                    .Select(fm => new SelectListItem
                    {
                        Value = fm.Id.ToString(),
                        Text = fm.Name
                    })
                    .Distinct()
                    .ToList();

                if (familyMemberNames.Any())
                {
                    ViewBag.FamilyMemberNames = new SelectList(familyMemberNames, "Value", "Text");
                }
                else
                {
                    ViewBag.FamilyMemberNames = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "Inga medlemmar i hushållet tillagda" }
            };
                }
            }

Controllers/DeleteController.cs
//using Microsoft.AspNetCore.Identity;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Authorization;
//using StoreQR.Data;
//using StoreQR.Interface;
//using System.Threading.Tasks;

//namespace StoreQR.Controllers
//{
//    public class DeleteController : Controller
//    {
//        private readonly ILogger<DeleteController> _logger;
//        private readonly DataAccess? _dataAccess;
//        private readonly UserManager<IdentityUser> _userManager;
//        private readonly SignInManager<IdentityUser> _signInManager;

//        public DeleteController(ILogger<DeleteController> logger,
//          DataAccess _dataAccess,
//          UserManager<IdentityUser> userManager,
//          SignInManager<IdentityUser> signInManager)
//        {
//            _logger = logger;
//            _dataAccess = _dataAccess ?? throw new ArgumentNullException(nameof(_dataAccess));
//            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
//            _signInManager = signInManager;
//        }

//        public IActionResult DeleteUser(string userId)
//        {
//            return View();
//        }

//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> ConfirmDeleteUser (string userId)
//        {
//            var success = _dataAccess != null && await _dataAccess.DeleteAllUserInfoByUserId(userId, _userManager, _signInManager);
//            if (success)
//            {
//                return RedirectToAction("Index", "Home");
//            }
//            else
//            {
//                return RedirectToAction("Error");
//            }
            


//        }
//    }
//}

Views/Clothing/Delete.cshtml
@model StoreQR.Models.ClothingItem
@{
    ViewData["Title"] = "Radera klädesplagg";
}

@if (User?.Identity?.IsAuthenticated == true)
{
    <div class="d-flex flex-row justify-content-center align-items-center mb-5">

        <div class="m-1 p-3 flex-column d-flex w-50 deleteClothing">
            <a asp-action="Index" class="mb-1 GoingBack"><i class="fa-solid fa-chevron-left"></i> Tillbaka</a>
            <div class=" d-flex flex-column mx-3 p-3 mt-3">
                <div class="DeleteClothingInfo">
                    <div class="d-flex justify-content-center align-items-center">
                        @if (!string.IsNullOrEmpty(Model.ClothingImage))
                        {
                            <img class="m-3" src="data:image/;base64,@Model.ClothingImage" alt="Bild av plagg" />
                        }
                        else
                        {
                            <img class="m-3" src="~/lib/example-pic.jpg" alt="Exempelbild" />
                        }
                    </div>
                    <h5 class="text-center mx-3 p-3">Beskrivning</h5>
                    <p class="text-center">@Model.ClothingName</p>
                    <p class="text-center">Storlek: @Model.ClothingSize</p>
                </div>
                <p class="mt-3">Om du raderar @Model.ClothingName så försvinner all information om klädesplagget såsom användare och förvaringsplats.</p>
                <form method="post" asp-area="" asp-controller="Clothing" asp-action="DeleteConfirmed">
                    <input type="hidden" asp-for="ClothingId" name="ClothingId" />

                    <button type="submit" class="btn btn-danger mt-1">Radera förvaringsutrymme</button>
                </form>
            </div>

        </div>

    </div>
}
else
{

    <span>Välkommen! Logga in för att få tillgång till StoreQR</span>
}

Views/Clothing/Edit.cshtml
@model List<StoreQR.Models.ClothingItem>
@{
    ViewData["Title"] = "Redigera klädesplagg";
}

@if (User?.Identity?.IsAuthenticated == true)
{
    <a asp-action="Index" class="mb-1 GoingBack"><i class="fa-solid fa-chevron-left"></i> Tillbaka</a>
    <div class="d-flex flex-row align-items-center justify-content-center mt-3 mb-5">
        @foreach (var item in Model)
        {
            <div class="m-1 p-0 flex-column d-flex w-50 editClothing">
                <div class="d-flex justify-content-center align-items-center">
                    @if (!string.IsNullOrEmpty(item.ClothingImage))
                    {
                        <img class="m-3 w-25" src="data:image/;base64,@item.ClothingImage" alt="Bild av plagg" />
                    }
                    else
                    {
                        <img class="m-3 w-25" src="~/lib/example-pic.jpg" alt="Exempelbild" />
                    }
            </div>
                <div class=" d-flex flex-column mx-3 p-3">
                    <h5 class="text-center mx-3 p-3">@item.ClothingName</h5>
                    <form method="post" asp-area="" asp-controller="Clothing" asp-action="Edit">
                        <input type="hidden" asp-for="@item.ClothingId" name="ClothingId" />
                        <input type="hidden" asp-for="@item.ClothingName" name="ClothingName" />
                        <div class="form-group">
                            @* <input type="hidden" asp-for="@item.ClothingUserId" name="ClothingUserId"/> *@
                            <label asp-for="@item.ClothingUserId" class="control-label mt-2 mb-2">Plagget tillhör:</label>
                            <select asp-for="@item.ClothingUserId" class="form-control" asp-items="ViewBag.FamilyMemberNames" name="ClothingUserId">
                                <option value="@item.ClothingUserId" selected="@item.ClothingUserId"></option>
                            </select>
                        </div>
                        <div class="form-group mt-3">
                            <label for="ClothingBrand">Märke:</label>
                            <input type="text" class="form-control" id="ClothingBrand" name="ClothingBrand" value="@item.ClothingBrand">
                        </div>
                        <div class="form-group mt-3">
                            <label for="ClothingSize">Storlek:</label>
                            <input type="text" class="form-control" id="ClothingSize" name="ClothingSize" value="@item.ClothingSize">
                        </div>
                        <div class="form-group mt-3">
                            <label for="ClothingColor">Färg:</label>
                            <input type="text" class="form-control" id="ClothingColor" name="ClothingColor" value="@item.ClothingColor">
                        </div>
                        <div class="form-group mt-3">
                                <label for="Season">Säsong:</label>
                            <input type="text" class="form-control" id="Season" name="Season" value="@item.Season">
                        </div>
                        <div class="form-group mt-3">
                                <label for="TypeOfClothing">Typ av plagg:</label>
                            <input type="text" class="form-control" id="TypeOfClothing" name="TypeOfClothing" value="@item.TypeOfClothing">
                        </div>
                        <div class="form-group mt-3">
                            <label asp-for="@item.StorageId" class="control-label mt-2 mb-2">Förvaras i:</label>
                            <select asp-for="@item.StorageId" class="form-control" asp-items="ViewBag.StorageNames" name="StorageId">
                                <option value="@item.StorageId" selected="@item.StorageId"></option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary m-3 justify-content-end">Spara</button>
                    </form>
                </div>

            </div>
        }

    </div>
}
else
{

    <span>Välkommen! Logga in för att få tillgång till StoreQR</span>
}

Views/Clothing/Index.cshtml
@model IPagedList<StoreQR.Models.ClothingViewModel>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@{
    ViewData["Title"] = "Kläder";
}


@if (User?.Identity?.IsAuthenticated == true)
{

    <div class="container d-flex flex-column align-items-center justify-content-center mb-5">
        <h2 class="mb-3 mt-3">Mina kläder</h2>
        @if (TempData.ContainsKey("DeleteSuccessMessage"))
        {
            <div class="alert alert-success" role="alert">
                @TempData["DeleteSuccessMessage"]
            </div>
        }
        @if (TempData.ContainsKey("DeleteErrorMessage"))
        {
            <div class="alert alert-success" role="alert">
                @TempData["DeleteErrorMessage"]
            </div>
        }
        <div class="d-flex align-items-center justify-content-center">
            <a class="btn btn-primary addClothesButton px-3" asp-area="" asp-controller="Clothing" asp-action="Create">Lägg till nytt plagg</a>
        </div>
        <div class="d-none d-md-block">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                     new PagedListRenderOptions
        {
            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" }
        })
        </div>
        <div class="d-flex flex-column flex-wrap flex-md-row flex-md-nowrap">
            <form class="mx-3" id="filterForm" method="get" action="@Url.Action("Index", "Clothing")">
                <fieldset class="d-flex flex-column justify-content-center align-items-center">
                    <div class="form-group">
                        <label class="control-label">Användare</label>
                        <select name="FamilyMemberName" class="form-control filter-dropdown family-dropdown">
                            <option value="">Alla användare</option>
                            @foreach (var distinctFamilyMemberName in ViewBag.DistinctFamilyMemberName)
                            {
                                <option value="@distinctFamilyMemberName">@distinctFamilyMemberName</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Märke</label>
                        <select name="ClothingBrand" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla märken</option>
                            @foreach (var distinctBrand in ViewBag.DistinctBrands)
                            {
                                <option value="@distinctBrand">@distinctBrand</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Storlek</label>
                        <select name="ClothingSize" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla storlekar</option>
                            @foreach (var distinctSize in ViewBag.DistinctSizes)
                            {
                                <option value="@distinctSize">@distinctSize</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Färg</label>
                        <select name="ClothingColor" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla färger</option>
                            @foreach (var distinctColor in ViewBag.DistinctColors)
                            {
                                <option value="@distinctColor">@distinctColor</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Säsong</label>
                        <select name="Season" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla säsonger</option>
                            @foreach (var distinctSeason in ViewBag.DistinctSeasons)
                            {
                                <option value="@distinctSeason">@distinctSeason</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Material</label>
                        <select name="ClothingMaterial" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla material</option>
                            @foreach (var distinctMaterial in ViewBag.DistinctMaterials)
                            {
                                <option value="@distinctMaterial">@distinctMaterial</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Typ av plagg</label>
                        <select name="TypeOfClothing" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla typer av plagg</option>
                            @foreach (var distinctTypeOfClothing in ViewBag.DistinctTypesOfClothing)
                            {
                                <option value="@distinctTypeOfClothing">@distinctTypeOfClothing</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label mt-3">Förvaringsutrymme</label>
                        <select name="StorageName" class="form-control filter-dropdown size-dropdown">
                            <option value="">Alla förvaringsutrymmen</option>
                            @foreach (var StorageUnitName in ViewBag.StorageUnitName)
                            {
                                <option value="@StorageUnitName">@StorageUnitName</option>
                            }
                        </select>
                    </div>

            
                <input type="submit" class="mt-3 btn-primary" value="Applicera filter">
                    <a href="@Url.Action("Index", "Clothing", new { ResetFilters = true })" class="mt-3 btn btn-warning">Återställ filter</a>
                </fieldset>
            </form>
            <div class="d-block d-md-none text-center">
                <div class="d-flex justify-content-center">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
                         new PagedListRenderOptions
            {
                LiElementClasses = new string[] { "page-item" },
                PageClasses = new string[] { "page-link" }
            })
            </div>
            </div>
            <div class="d-flex flex-row align-items-center justify-content-center flex-wrap">
              
            @foreach (var item in Model)
            {
                <div class="card ClothingCard m-1 p-0 flex-column d-flex">
                    <div class="d-flex justify-content-center align-items-center">
                            @if (!string.IsNullOrEmpty(item.ClothingImage))
                            {
                                <img class="m-3" src="data:image/;base64,@item.ClothingImage" alt="Bild av plagg" />
                            }
                            else
                            {
                                <img class="m-3" src="~/lib/example-pic.jpg" alt="Exempelbild" />
                            }
                        </div>
                    <div class="card-body d-flex flex-column mx-3 p-3 align-items-center justify-content-center ClothingCardBody">
                            <h5 class="card-title text-center mx-3 p-3">@item.ClothingName</h5>
                            <p class="card-text mx-3 text-center">Användare: @item.FamilyMemberName</p>
                            <p class="card-text mx-3 text-center">Storlek: @item.ClothingSize</p>
@*                             <p class="card-text mx-3 p-3 text-center">Märke: @item.ClothingBrand</p>
                            
                            <p class="card-text mx-3 p-3 text-center">Färg: @item.ClothingColor</p>
                            <p class="card-text mx-3 p-3 text-center">Material: @item.ClothingMaterial</p>
                        <p class="card-text mx-3 p-3 text-center">Säsong: @item.Season</p> *@
                       @*  <p class="card-text mx-3 p-3 text-center">Typ av plagg: @item.TypeOfClothing</p> *@
                        <p class="card-text mx-1 text-center">@item.StorageName</p>
                        <a class="btn btn-primary m-1 justify-content-end " asp-area="" asp-controller="Clothing" asp-action="Edit" asp-route-ClothingId="@item.ClothingId">Redigera</a>
                        <a class="btn btn-warning mx-1 justify-content-end" asp-area="" asp-controller="Clothing" asp-action="Delete" asp-route-ClothingId="@item.ClothingId">Radera</a>

                    </div>

                </div>
            }
            </div>
         
           
        </div>
       
    </div>

}
else
{

    <span>Välkommen! Logga in för att få tillgång till StoreQR</span>
}


<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Hämta alla filterelement
        var filterForm = document.getElementById("filterForm");

        // Lägg på ett change-event på varje dropdown
        filterForm.addEventListener("change", function () {
            // Skicka formuläret om innehållet i dropdownen ändras
            filterForm.submit();
        });
    });

</script>